before_script: '
cd "/home/gitlab_ci_multi_runner/data/$CI_PROJECT_DIR"
# Setup commands:
# apt-get update - needed?
# apt-get install python python-pip - needed?
pip install -r requirements.txt
pip install coveralls
popd
# Sync your DB for django projects
python manage.py syncdb --noinput
'

build_id2:
    script: '
cd "/home/gitlab_ci_multi_runner/data/$CI_PROJECT_DIR"
# Run commands:
python manage.py test
coverage run --source=. manage.py test
coveralls
'
