# docker compose config
# http://docs.docker.com/compose/
#
id2:
  build: .
  expose:
    - "8000"
  links:
    - mysql
    - neo4j
neo4j:
  image: tpires/neo4j
  cap_add:
    - SYS_RESOURCE
mysql:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER:     id2
    MYSQL_PASSWORD: id2
    MYSQL_DATABASE: id2