# docker compose config
# http://docs.docker.com/compose/
#
id2:
  build: .
  expose:
    - "8000"
  links:
    - postgres
    - elasticsearch
postgres:
  image: postgres
  volumes:
    - 'db/:/var/lib/postgresql/data'
  environment:
    POSTGRES_USER:     id2
    POSTGRES_PASSWORD: id2
    POSTGRES_DATABASE: id2
elasticsearch:
  image: elasticsearch
