# docker compose config
# http://docs.docker.com/compose/
#
# this is the production configuration
# if you're looking for data import config, use dataimports.yml as your
# compose file
# 
id2:
  build: .
  expose:
    - "8000"
  links:
    - postgres
    - elasticsearch
  volumes:
    - "settings/settings_local.py-docker:/usr/src/id2/settings/settings_local.py"

# development version
id2dev:
  build: .
  expose:
    - "8000"
  links:
    - postgres
    - elasticsearch
  volumes:
    - "settings/settings_local.py-docker:/usr/src/id2/settings/settings_local.py"
    # explicitly bind-mounting each and every directory
    # because bower
    - "./tools:/usr/src/id2/tools"
    - "./core:/usr/src/id2/core"
    - "./settings:/usr/src/id2/settings"
    - "./locale:/usr/src/id2/locale"
    - "./doc:/usr/src/id2/doc"
    - "./projects:/usr/src/id2/projects"
    - "./robots:/usr/src/id2/robots"
    - "./data:/usr/src/id2/data"
    - "./ticket:/usr/src/id2/ticket"
    - "./templates:/usr/src/id2/templates"
    - "./search:/usr/src/id2/search"
    - "./id:/usr/src/id2/id"
    - "./podaci:/usr/src/id2/podaci"
    - "./static/js:/usr/src/id2/static/js"
    - "./static/css:/usr/src/id2/static/css"
    - "./static/html:/usr/src/id2/static/html"
    - "./static/less:/usr/src/id2/static/less"
    - "./static/img:/usr/src/id2/static/img"
    
# dataimports version
id2dataimports:
  build: .
  expose:
    - "8000"
  links:
    - postgres
    - elasticsearch
  volumes:
    - "./:/usr/src/id2/"
    - "settings/settings_local.py-docker:/usr/src/id2/settings/settings_local.py"
    - "../export-prod/:/data"
    - "../google_appengine/:/usr/src/google_appengine/"
    - "../investigative-dashboard/:/usr/src/id/"
  command: /bin/date

# postgres
postgres:
  image: postgres
  volumes:
    - 'db/:/var/lib/postgresql/data'
  environment:
    POSTGRES_USER:     id2
    POSTGRES_PASSWORD: id2
    POSTGRES_DATABASE: id2

# elasticsearch    
elasticsearch:
  image: elasticsearch
