# Docker compose config
# http://docs.docker.com/compose/
version: "2"

networks:
  serverconfig_frontend:
    external:
      name: serverconfig_frontend
  id2internal:
    driver: bridge

  # for kuvert-supported encrypted/signed e-mails
  postar_default:
    external:
      name: postar_default

services:
  postgres:
    image: postgres:9.4
    volumes:
      - '/srv/data/live/postgres/id2/:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER:     id2
      POSTGRES_PASSWORD: id2
      POSTGRES_DATABASE: id2
    networks:
      - id2internal

  queue:
    restart: always
    image: id/api
    build: ./
    command: 'python manage.py queue'
    volumes:
      - "/srv/logs/id2/:/var/log/id2/"
    env_file:
      - id.env
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - id2internal
      - postar_default

  api:
    restart: always
    image: id/api
    command: gunicorn -w 5 -b 0.0.0.0:8080 -t 60 --keep-alive 5 --log-level info --log-file - api_v3.wsgi:application
    volumes:
      - "/srv/data/live/podaci/:/id/data"
      - "/srv/logs/id2/:/var/log/id2/"
      - "/srv/data/dumps/:/dumps/"
      - "/srv/data/live/idstatic/:/id/build/"
    env_file:
      - id.env
    depends_on:
      - queue
    links:
      - postgres
    networks:
      - id2internal
      - postar_default

  web:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    expose:
     - 8000
    depends_on:
      - api
    networks:
      - id2internal
      - serverconfig_frontend
