# docker compose config
# http://docs.docker.com/compose/
version: "2"

services:
  web:
    build: .
    command: gunicorn -w 5 -b 0.0.0.0:8000 -t 60 --keep-alive 5 --log-level info --log-file - wsgi:application
    ports:
      - "8000:8000"
    links:
      - postgres
    volumes:
      - "./podaci-data/:/data"
      - "./log/:/var/log/id2/"
    env_file:
      - id.env

  # postgres
  # TODO FIXME before we go to production with this!
  postgres:
    image: postgres:9.4
    volumes:
      - './db/:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER:     id2
      POSTGRES_PASSWORD: id2
      POSTGRES_DATABASE: id2
