# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-17 15:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, null=True),
        ),
    ]
