# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-24 12:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v3', '0000_squashed_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=70)),
                ('request_type', models.CharField(db_index=True, max_length=70)),
                ('status', models.CharField(db_index=True, default=b'new', max_length=70)),
                ('sensitive', models.BooleanField(default=False)),
                ('whysensitive', models.CharField(null=True, max_length=150)),
                ('deadline_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('background', models.TextField(max_length=1000)),
                ('first_name', models.CharField(null=True, max_length=512)),
                ('last_name', models.CharField(null=True, max_length=512)),
                ('born_at', models.DateTimeField(null=True)),
                ('connections', models.TextField(null=True)),
                ('sources', models.TextField(null=True)),
                ('business_activities', models.TextField(null=True, max_length=1000)),
                ('initial_information', models.TextField(null=True, max_length=1000)),
                ('company_name', models.CharField(null=True, max_length=512)),
                ('country', models.CharField(db_index=True, null=True, max_length=100)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_tickets', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(db_index=True, through='api_v3.Responder', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='responder',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responders', to='api_v3.Ticket'),
        ),
        migrations.AddField(
            model_name='responder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='responder',
            unique_together=set([('user', 'ticket')]),
        ),
    ]
