# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-30 15:06
from __future__ import unicode_literals

import core.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_v3', '0002_added_new_ticket_attachment_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            bases=(models.Model, core.mixins.NotificationMixin),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='upload',
            field=models.FileField(upload_to=b'./data/attachments/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='activities',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='company_name',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='first_name',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='initial_information',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='last_name',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='comment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api_v3.Ticket'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
