# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-17 15:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v3', '0003_added_new_ticket_comment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, null=True),
        ),
    ]
