# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-17 19:01


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v3', '0003_added_new_ticket_comment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sent_notifications_at',
            field=models.DateTimeField(null=True),
        ),
    ]
