# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-09 18:49


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v3', '0005_added_notification_timestamp_to_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='responder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
