# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-08 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    SQL = """
    insert into api_v3_ticket (
        id,
        status,
        request_type,
        created_at,
        updated_at,
        deadline_at,
        sensitive,
        whysensitive,
        requester_id,
        background,
        connections,
        company_name,
        country,
        first_name,
        last_name,
        born_at,
        business_activities,
        initial_information,
        kind
    )
    select
        ticket_ticket.id,
        ticket_ticket.status,
        ticket_ticket.requester_type as request_type,
        ticket_ticket.created as created_at,
        ticket_ticket.status_updated as updated_at,
        ticket_ticket.deadline as deadline_at,
        ticket_ticket.sensitive,
        ticket_ticket.whysensitive,
        ticket_ticket.requester_id,

        coalesce(
            ticket_otherticket.question,
            ticket_companyticket.background,
            ticket_personticket.background
        ) as background,

        coalesce(
            ticket_companyticket.connections,
            ticket_personticket.aliases,
            ticket_personticket.family
        ) as connections,

        ticket_companyticket.name as company_name,
        ticket_companyticket.country,

        ticket_personticket.name as first_name,
        ticket_personticket.surname as last_name,
        ticket_personticket.dob as born_at,
        ticket_personticket.business_activities,
        ticket_personticket.initial_information,

        case
            when
                (ticket_otherticket.ticket_ptr_id is not null)
                    then 'other'
            when
                (ticket_companyticket.ticket_ptr_id is not null)
                    then 'company_ownership'
            when
                (ticket_personticket.ticket_ptr_id is not null)
                    then 'person_ownership'
        end as kind

        from
            ticket_ticket

        full outer join
            ticket_companyticket on (
                ticket_ticket.id = ticket_companyticket.ticket_ptr_id)
        full outer join
            ticket_personticket on (
                ticket_ticket.id = ticket_personticket.ticket_ptr_id)
        full outer join
            ticket_otherticket on (
                ticket_ticket.id = ticket_otherticket.ticket_ptr_id)
    """

    dependencies = [
        ('api_v3', '0005_added_notification_timestamp_to_ticket'),
    ]

    operations = [
        migrations.RunSQL(SQL)
    ]
