# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-23 20:53


import api_v3.models.profile
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v3', '0010_drop_profile_not_null'),
    ]

    DROP_NOT_USERID_NULL_SQL = """
        ALTER TABLE api_v3_subscriber ALTER COLUMN user_id DROP NOT NULL;
        """

    operations = [
        migrations.RunSQL(DROP_NOT_USERID_NULL_SQL),
        migrations.AddField(
            model_name='subscriber',
            name='email',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='subscriber',
            unique_together=set([('email', 'ticket', 'user')]),
        ),
    ]
