# Generated by Django 3.0.3 on 2020-02-25 15:13

from django.contrib.postgres.fields import ArrayField
from django.db import migrations, models

from api_v3.models import Ticket


class Migration(migrations.Migration):

    dependencies = [
        ('api_v3', '0011_add_email_and_drop_user_not_null_on_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='countries',
            field=ArrayField(base_field=models.CharField(max_length=255, null=True), db_index=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='ticket',
            name='identifier',
            field=models.CharField(blank=False, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='member_center',
            field=models.CharField(blank=False, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=Ticket.PRIORITIES, db_index=True, default='default', max_length=70),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tags',
            field=ArrayField(base_field=models.CharField(max_length=255, null=True), db_index=True, default=list, size=None),
        ),
    ]
